pandas는 전처리와 , 통계분석(eda) explorely data analisty

In [1]:
import pandas as pd

In [2]:
pd.__version__ # 0. 버전은 내맘대로 바꿀 수 있다.

'0.23.3'

In [3]:
!pip install -U pandas

Requirement already up-to-date: pandas in c:\programdata\anaconda3\lib\site-packages (0.23.3)
Requirement not upgraded as not directly required: numpy>=1.9.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (1.14.0)
Requirement not upgraded as not directly required: python-dateutil>=2.5.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.6.1)
Requirement not upgraded as not directly required: pytz>=2011k in c:\programdata\anaconda3\lib\site-packages (from pandas) (2017.3)
Requirement not upgraded as not directly required: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.5.0->pandas) (1.11.0)

tensorflow-gpu 1.7.0 has requirement tensorboard<1.8.0,>=1.7.0, but you'll have tensorboard 1.8.0 which is incompatible.
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

In [4]:
# read  -> data frame을 불러온다 .
# 판다스는 기본적인 프레임이 데이터 프레임

df = pd.read_csv('data-netflix.csv')
df.head()

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80

In [5]:
type(df) #DataFrame class (pascal 방식으로 표현되었기 때문에)

pandas.core.frame.DataFrame

In [6]:
dir(df) #판다스는 전처리, eda

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_SLICEMAP',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_wrap__',
 '__bool__',
 '__bytes__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__unicode__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_only_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_box_col_values',
 '_box_item_values',
 '_builtin_table',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_percentile',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_combine_const',
 '_combine_frame',
 '_combine_match_columns',
 '_combine_match_index',
 '_compare_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_for_slice',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_create_indexer',
 '_cython_table',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_expand_axes',
 '_find_valid_index',
 '_from_arrays',
 '_from_axes',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values',
 '_getitem_array',
 '_getitem_column',
 '_getitem_frame',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_iget_item_cache',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_dict',
 '_init_mgr',
 '_init_ndarray',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_cython_func',
 '_is_datelike_mixed_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_join_compat',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_axis',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_series',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_setup_axes',
 '_shallow_copy',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_take',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_unpickle_frame_compat',
 '_unpickle_matrix_compat',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'as_matrix',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'axes',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'clip_lower',
 'clip_upper',
 'columns',
 'combine',
 'combine_first',
 'compound',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'from_dict',
 'from_records',
 'ftypes',
 'ge',
 'get',
 'get_dtype_counts',
 'get_ftype_counts',
 'get_values',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'ix',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rating',
 'ratingDescription',
 'ratingLevel',
 'rdiv',
 'reindex',
 'reindex_axis',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'title',
 'to_clipboard',
 'to_csv',
 'to_dense',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_msgpack',
 'to_panel',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sparse',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'values',
 'var',
 'where',
 'xs']

In [7]:
df

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80
5,Supernatural,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,95.0,80
6,Breaking Bad,TV-MA,For mature audiences. May not be suitable for...,110,2013,97.0,80
7,The Vampire Diaries,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2017,91.0,80
8,The Walking Dead,TV-MA,For mature audiences. May not be suitable for...,110,2015,98.0,80
9,Pretty Little Liars,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,96.0,80
10,Once Upon a Time,TV-PG,Parental guidance suggested. May not be suitab...,70,2016,98.0,80
11,Sherlock,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,95.0,80
12,Death Note,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2006,77.0,80
13,Naruto,TV-PG,Parental guidance suggested. May not be suitab...,70,2008,88.0,80
14,The Hunter,R,language and brief violence,100,2011,NaN,82
15,Lottie Dottie Chicken,TV-Y,Suitable for all ages.,10,2009,NaN,82
16,Arrow,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2015,96.0,80
17,Black Mirror,TV-MA,For mature audiences. May not be suitable for...,110,2016,80.0,80
18,The Originals,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,74.0,80
19,The 100,NR,This movie has not been rated.,124,2016,97.0,80
20,Masha and the Bear,TV-Y,Suitable for all ages.,10,2013,81.0,80
21,"Ã“ Pai, Ã“ - Look at This",TV-MA,For mature audiences. May not be suitable for...,110,2007,NaN,82
22,Nymphomaniac: Volume 1,NR,This movie has not been rated.,124,2013,NaN,82
23,Hunter X Hunter (2011),NR,This movie has not been rated.,124,2013,57.0,80
24,Marvel's Luke Cage,TV-MA,For mature audiences. May not be suitable for...,110,2016,95.0,80
25,Marvel's Iron Fist,TV-MA,NaN,110,2017,98.0,80
26,Narcos,TV-MA,For mature audiences. May not be suitable for...,110,2016,94.0,80
27,The Flash,TV-PG,Parental guidance suggested. May not be suitab...,70,2016,98.0,80
28,The Seven Deadly Sins,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,NaN,82
29,Scream,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,NaN,82
...,...,...,...,...,...,...,...
970,Annie,PG,adult content and mld violence,60,1982,68.0,80
971,An American Tail: Fievel Goes West,G,General Audiences. Suitable for all ages.,35,1991,NaN,82
972,D2: The Mighty Ducks,PG,some mild language and rough hockey action,60,1994,70.0,80
973,"Honey, I Shrunk the Kids",PG,Parental guidance suggested. May not be suitab...,60,1989,80.0,80
974,The Iron Giant,PG,fantasy action and mild language,60,1999,83.0,80
975,The Fox and the Hound 2,G,General Audiences. Suitable for all ages.,35,2006,NaN,82
976,Air Buddies,PG,"some mild, rude humor",60,2006,NaN,82
977,Dr. Dolittle: Tail to the Chief,PG,brief mild language and some rude behavior,60,2008,NaN,82
978,Flicka 2,PG,some reckless behavior,60,2010,NaN,82
979,H2O: Just Add Water,TV-PG,Parental guidance suggested. May not be suitab...,70,2009,74.0,80
980,The Gruffalo,TV-Y,Suitable for all ages.,10,2009,NaN,82
981,Dolphin Tale,PG,some mild thematic elements,60,2011,NaN,82
982,Pound Puppies,TV-Y,Suitable for all ages.,10,2013,NaN,82
983,Beverly Hills Chihuahua 3: Viva La Fiesta!,G,General Audiences. Suitable for all ages.,35,2012,NaN,82
984,The Magic School Bus,TV-Y,Suitable for all ages.,10,1997,81.0,80
985,Step Dogs,TV-PG,Parental guidance suggested. May not be suitab...,70,2013,NaN,82
986,PokÃ©mon: Indigo League,TV-Y,Suitable for all ages.,10,2000,74.0,80
987,Mia and Me,TV-Y,Suitable for all ages.,10,2015,NaN,82
988,Paddington,PG,mild action and rude humor,60,2014,70.0,80
989,Russell Madness,PG,some rude humor and sports action,60,2015,NaN,82
990,My Animal Friends,TV-Y,Suitable for all ages.,10,2013,NaN,82
991,Dawn of the Croods,TV-Y7,Suitable for children ages 7 and older,41,2017,72.0,80
992,Alpha and Omega: Dino Digs,TV-G,Suitable for all ages.,35,2016,NaN,82
993,Wiener Dog Internationals,G,General Audiences. Suitable for all ages.,35,2015,NaN,82
994,Pup Star,G,General Audiences. Suitable for all ages.,35,2016,NaN,82
995,The BFG,PG,"for action/peril, some scary moments and brief...",60,2016,97.0,80
996,The Secret Life of Pets,PG,for action and some rude humor,60,2016,NaN,81
997,Precious Puppies,TV-G,Suitable for all ages.,35,2003,NaN,82
998,Beary Tales,TV-G,Suitable for all ages.,35,2013,NaN,82
999,Growing Up Wild,G,NaN,35,2016,80.0,80

# 기본 5개 분석

In [8]:
df.info() 
# 컬럼은 속성(attribute) 
# row는 관측치 observation 

# non-null -> 누락된 데이터가 없다.

# pandas 데이터 형태는 크게 두 가지 (숫자형, 문자형)
# 판다스는 실생활에서 복소수를 잘 상용안하기 때문에 bool int 상속 받기 때문에 int 
# title- > string
# rating -> string
# level -> string
# 판다스는 모든 데이터를 메모리에 올린다. -> 속도가 빨라
# 단점: 메모리보다 큰 범위를 해결 할 수없다 
# 엄청 큰 데이터는 pd 사용하기 어려워
# dask- > 디스크기반이기 때문에 가능해 

#판다스 후 봐야할 5가지
# data 잘 불러왔는디 확인
# info 
# describe
# sample

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
title                1000 non-null object
rating               1000 non-null object
ratingLevel          941 non-null object
ratingDescription    1000 non-null int64
release year         1000 non-null int64
user rating score    605 non-null float64
user rating size     1000 non-null int64
dtypes: float64(1), int64(3), object(3)
memory usage: 54.8+ KB

In [9]:
df.describe() 
# like a summary  
# 판다스 만든 사람이 r좋아했어 그른디 파이썬을 좋아했어 
# 숫자형있는 애만 summary나온다.

       ratingDescription  release year  user rating score  user rating size
count         1000.00000   1000.000000         605.000000       1000.000000
mean            67.36600   2010.335000          84.094215         80.783000
std             30.78561      8.877927          12.344371          0.973066
min             10.00000   1940.000000          55.000000         80.000000
25%             35.00000   2007.000000          75.000000         80.000000
50%             60.00000   2015.000000          88.000000         80.000000
75%             90.00000   2016.000000          95.000000         82.000000
max            124.00000   2017.000000          99.000000         82.000000

In [10]:
df.head().info() # dataframe이기 때문에 info() 사용 가능

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
title                5 non-null object
rating               5 non-null object
ratingLevel          5 non-null object
ratingDescription    5 non-null int64
release year         5 non-null int64
user rating score    4 non-null float64
user rating size     5 non-null int64
dtypes: float64(1), int64(3), object(3)
memory usage: 360.0+ bytes

In [12]:
df.head().describe() # 보통 달라

       ratingDescription  release year  user rating score  user rating size
count           5.000000      5.000000           4.000000          5.000000
mean           86.000000   2009.600000          93.000000         80.400000
std            11.401754      5.176872           7.571878          0.894427
min            70.000000   2004.000000          82.000000         80.000000
25%            80.000000   2006.000000          91.000000         80.000000
50%            90.000000   2008.000000          96.000000         80.000000
75%            90.000000   2014.000000          98.000000         80.000000
max           100.000000   2016.000000          98.000000         82.000000

In [13]:
df.tail().describe()

       ratingDescription  release year  user rating score  user rating size
count           5.000000      5.000000           2.000000               5.0
mean           45.000000   2012.800000          88.500000              81.0
std            13.693064      5.630275          12.020815               1.0
min            35.000000   2003.000000          80.000000              80.0
25%            35.000000   2013.000000          84.250000              80.0
50%            35.000000   2016.000000          88.500000              81.0
75%            60.000000   2016.000000          92.750000              82.0
max            60.000000   2016.000000          97.000000              82.0

In [25]:
df.sample() # 랜덤하게 뽑는다.

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
341,How to Get Away with Murder,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,95.0,80

In [26]:
df.sample(10) #그냥 느낌 보는거야

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
459,The Vampire Diaries,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2017,91.0,80
970,Annie,PG,adult content and mld violence,60,1982,68.0,80
485,American Crime,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,NaN,82
788,The Pirate Fairy,G,General Audiences. Suitable for all ages.,35,2014,57.0,80
501,Scooby-Doo,PG,"some rude humor, language and some scary action",60,2002,86.0,80
796,Quackerz,PG,"rude and suggestive humor, and some action",60,2016,NaN,82
525,Thomas & Friends: King of the Railway,TV-G,Suitable for all ages.,35,2013,NaN,82
19,The 100,NR,This movie has not been rated.,124,2016,97.0,80
95,Sand Castle,TV-MA,NaN,110,2017,89.0,80
149,Almost Adults,NR,This movie has not been rated.,124,2016,NaN,82

In [27]:
# 원래 처음에 데이터 다 보는디 보기 귀찮으니 느낌볼려고 sample

In [43]:
df2 = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")

In [44]:
df2 
# row는 관측치가 나와야한다. column은 변수 구분된 애로 
# 2차원 형태로 나와야한다. 
# db는 참조무결성으로 인해 테이블로 쪼개었지만, 
# 이 데이터 분석은 쪼개진 데이터를 붙여야한다.

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
5    4.6  3.4  1.4  0.3     Iris-setosa
6    5.0  3.4  1.5  0.2     Iris-setosa
7    4.4  2.9  1.4  0.2     Iris-setosa
8    4.9  3.1  1.5  0.1     Iris-setosa
9    5.4  3.7  1.5  0.2     Iris-setosa
10   4.8  3.4  1.6  0.2     Iris-setosa
11   4.8  3.0  1.4  0.1     Iris-setosa
12   4.3  3.0  1.1  0.1     Iris-setosa
13   5.8  4.0  1.2  0.2     Iris-setosa
14   5.7  4.4  1.5  0.4     Iris-setosa
15   5.4  3.9  1.3  0.4     Iris-setosa
16   5.1  3.5  1.4  0.3     Iris-setosa
17   5.7  3.8  1.7  0.3     Iris-setosa
18   5.1  3.8  1.5  0.3     Iris-setosa
19   5.4  3.4  1.7  0.2     Iris-setosa
20   5.1  3.7  1.5  0.4     Iris-setosa
21   4.6  3.6  1.0  0.2     Iris-setosa
22   5.1  3.3  1.7  0.5     Iris-setosa
23   4.8  3.4  1.9  0.2     Iris-setosa
24   5.0  3.0  1.6  0.2     Iris-setosa
25   5.0  3.4  1.6  0.4     Iris-setosa
26   5.2  3.5  1.5  0.2     Iris-setosa
27   5.2  3.4  1.4  0.2     Iris-setosa
28   4.7  3.2  1.6  0.2     Iris-setosa
29   4.8  3.1  1.6  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
119  6.9  3.2  5.7  2.3  Iris-virginica
120  5.6  2.8  4.9  2.0  Iris-virginica
121  7.7  2.8  6.7  2.0  Iris-virginica
122  6.3  2.7  4.9  1.8  Iris-virginica
123  6.7  3.3  5.7  2.1  Iris-virginica
124  7.2  3.2  6.0  1.8  Iris-virginica
125  6.2  2.8  4.8  1.8  Iris-virginica
126  6.1  3.0  4.9  1.8  Iris-virginica
127  6.4  2.8  5.6  2.1  Iris-virginica
128  7.2  3.0  5.8  1.6  Iris-virginica
129  7.4  2.8  6.1  1.9  Iris-virginica
130  7.9  3.8  6.4  2.0  Iris-virginica
131  6.4  2.8  5.6  2.2  Iris-virginica
132  6.3  2.8  5.1  1.5  Iris-virginica
133  6.1  2.6  5.6  1.4  Iris-virginica
134  7.7  3.0  6.1  2.3  Iris-virginica
135  6.3  3.4  5.6  2.4  Iris-virginica
136  6.4  3.1  5.5  1.8  Iris-virginica
137  6.0  3.0  4.8  1.8  Iris-virginica
138  6.9  3.1  5.4  2.1  Iris-virginica
139  6.7  3.1  5.6  2.4  Iris-virginica
140  6.9  3.1  5.1  2.3  Iris-virginica
141  5.8  2.7  5.1  1.9  Iris-virginica
142  6.8  3.2  5.9  2.3  Iris-virginica
143  6.7  3.3  5.7  2.5  Iris-virginica
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

# header = None

In [45]:
# 이 데이터는 헤더가 없다.
# 그래서 
df2 = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", header= None)

In [46]:
df2 # 판다스 데이터 프레임으로 인덱스를 붙여줬다. 
    # 컬럼 네임 0, 1, 2, 3, 4 -> ==인덱스 [인덱싱, 슬라이싱 가능 즉, 시퀀시]
    # 한줄 한열 컴럼은 serise
    #  row -> 인덱스 
    # 시퀀스 하게 나옴

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
5    5.4  3.9  1.7  0.4     Iris-setosa
6    4.6  3.4  1.4  0.3     Iris-setosa
7    5.0  3.4  1.5  0.2     Iris-setosa
8    4.4  2.9  1.4  0.2     Iris-setosa
9    4.9  3.1  1.5  0.1     Iris-setosa
10   5.4  3.7  1.5  0.2     Iris-setosa
11   4.8  3.4  1.6  0.2     Iris-setosa
12   4.8  3.0  1.4  0.1     Iris-setosa
13   4.3  3.0  1.1  0.1     Iris-setosa
14   5.8  4.0  1.2  0.2     Iris-setosa
15   5.7  4.4  1.5  0.4     Iris-setosa
16   5.4  3.9  1.3  0.4     Iris-setosa
17   5.1  3.5  1.4  0.3     Iris-setosa
18   5.7  3.8  1.7  0.3     Iris-setosa
19   5.1  3.8  1.5  0.3     Iris-setosa
20   5.4  3.4  1.7  0.2     Iris-setosa
21   5.1  3.7  1.5  0.4     Iris-setosa
22   4.6  3.6  1.0  0.2     Iris-setosa
23   5.1  3.3  1.7  0.5     Iris-setosa
24   4.8  3.4  1.9  0.2     Iris-setosa
25   5.0  3.0  1.6  0.2     Iris-setosa
26   5.0  3.4  1.6  0.4     Iris-setosa
27   5.2  3.5  1.5  0.2     Iris-setosa
28   5.2  3.4  1.4  0.2     Iris-setosa
29   4.7  3.2  1.6  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
120  6.9  3.2  5.7  2.3  Iris-virginica
121  5.6  2.8  4.9  2.0  Iris-virginica
122  7.7  2.8  6.7  2.0  Iris-virginica
123  6.3  2.7  4.9  1.8  Iris-virginica
124  6.7  3.3  5.7  2.1  Iris-virginica
125  7.2  3.2  6.0  1.8  Iris-virginica
126  6.2  2.8  4.8  1.8  Iris-virginica
127  6.1  3.0  4.9  1.8  Iris-virginica
128  6.4  2.8  5.6  2.1  Iris-virginica
129  7.2  3.0  5.8  1.6  Iris-virginica
130  7.4  2.8  6.1  1.9  Iris-virginica
131  7.9  3.8  6.4  2.0  Iris-virginica
132  6.4  2.8  5.6  2.2  Iris-virginica
133  6.3  2.8  5.1  1.5  Iris-virginica
134  6.1  2.6  5.6  1.4  Iris-virginica
135  7.7  3.0  6.1  2.3  Iris-virginica
136  6.3  3.4  5.6  2.4  Iris-virginica
137  6.4  3.1  5.5  1.8  Iris-virginica
138  6.0  3.0  4.8  1.8  Iris-virginica
139  6.9  3.1  5.4  2.1  Iris-virginica
140  6.7  3.1  5.6  2.4  Iris-virginica
141  6.9  3.1  5.1  2.3  Iris-virginica
142  5.8  2.7  5.1  1.9  Iris-virginica
143  6.8  3.2  5.9  2.3  Iris-virginica
144  6.7  3.3  5.7  2.5  Iris-virginica
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [34]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
5.1            149 non-null float64
3.5            149 non-null float64
1.4            149 non-null float64
0.2            149 non-null float64
Iris-setosa    149 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB

In [35]:
df2.head()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [36]:
df2.describe()

              5.1         3.5         1.4         0.2
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [37]:
df2.sample()

    5.1  3.5  1.4  0.2  Iris-setosa
48  5.0  3.3  1.4  0.2  Iris-setosa

In [59]:
df = pd.read_csv("data-netflix.csv", header=2)

In [60]:
df.info() 
#헤더의 위에거를 다 삭제 # 빅데이터에서는 한 두개 영향이 크게 안미침  
# small data에서는 크게 미침

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 998 entries, 0 to 997
Data columns (total 7 columns):
Lucky Number Slevin                                   998 non-null object
R                                                     998 non-null object
strong violence, sexual content and adult language    939 non-null object
100                                                   998 non-null int64
2006                                                  998 non-null int64
NA                                                    604 non-null float64
82                                                    998 non-null int64
dtypes: float64(1), int64(3), object(3)
memory usage: 54.7+ KB

In [61]:
df = pd.read_csv("data-netflix.csv", index_col="title")
#기준 # index는 헥싱이랑 똑같다. -> == dict

In [64]:
df.sample(10)

,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
title,,,,,,
Arrow,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2015,96.0,80
"Honey, I Shrunk the Kids",PG,Parental guidance suggested. May not be suitab...,60,1989,80.0,80
Raising Hope,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2013,73.0,80
Agent F.O.X.,PG,Parental guidance suggested. May not be suitab...,60,2014,NaN,82
O Amor no DivÃ£,TV-MA,NaN,110,2016,NaN,82
Kung Fu Panda,PG,sequences of martial arts action,60,2008,91.0,80
Little Baby Bum: Nursery Rhyme Friends,TV-Y,Suitable for all ages.,10,2016,NaN,82
Annie,PG,adult content and mld violence,60,1982,68.0,80
Once Upon a Time,TV-PG,Parental guidance suggested. May not be suitab...,70,2016,98.0,80
The Prince of Egypt,PG,intense scenes dealing with strong content,60,1998,81.0,80

In [65]:
df = pd.read_csv("data-netflix.csv", usecols= ['title', 'rating', 'release year']) 
# 아주 안좋아 가져올 때 부터 버리는건 바보 또는 초 전문가
df # 메모리에 올리니깐 , -> knowledege picture ~~

                                          title rating  release year
0                                  White Chicks  PG-13          2004
1                           Lucky Number Slevin      R          2006
2                                Grey's Anatomy  TV-14          2016
3                                  Prison Break  TV-14          2008
4                         How I Met Your Mother  TV-PG          2014
5                                  Supernatural  TV-14          2016
6                                  Breaking Bad  TV-MA          2013
7                           The Vampire Diaries  TV-14          2017
8                              The Walking Dead  TV-MA          2015
9                           Pretty Little Liars  TV-14          2016
10                             Once Upon a Time  TV-PG          2016
11                                     Sherlock  TV-14          2016
12                                   Death Note  TV-14          2006
13                                       Naruto  TV-PG          2008
14                                   The Hunter      R          2011
15                        Lottie Dottie Chicken   TV-Y          2009
16                                        Arrow  TV-14          2015
17                                 Black Mirror  TV-MA          2016
18                                The Originals  TV-14          2016
19                                      The 100     NR          2016
20                           Masha and the Bear   TV-Y          2013
21                    Ã“ Pai, Ã“ - Look at This  TV-MA          2007
22                       Nymphomaniac: Volume 1     NR          2013
23                       Hunter X Hunter (2011)     NR          2013
24                           Marvel's Luke Cage  TV-MA          2016
25                           Marvel's Iron Fist  TV-MA          2017
26                                       Narcos  TV-MA          2016
27                                    The Flash  TV-PG          2016
28                        The Seven Deadly Sins  TV-14          2016
29                                       Scream  TV-14          2016
..                                          ...    ...           ...
970                                       Annie     PG          1982
971          An American Tail: Fievel Goes West      G          1991
972                        D2: The Mighty Ducks     PG          1994
973                    Honey, I Shrunk the Kids     PG          1989
974                              The Iron Giant     PG          1999
975                     The Fox and the Hound 2      G          2006
976                                 Air Buddies     PG          2006
977             Dr. Dolittle: Tail to the Chief     PG          2008
978                                    Flicka 2     PG          2010
979                         H2O: Just Add Water  TV-PG          2009
980                                The Gruffalo   TV-Y          2009
981                                Dolphin Tale     PG          2011
982                               Pound Puppies   TV-Y          2013
983  Beverly Hills Chihuahua 3: Viva La Fiesta!      G          2012
984                        The Magic School Bus   TV-Y          1997
985                                   Step Dogs  TV-PG          2013
986                     PokÃ©mon: Indigo League   TV-Y          2000
987                                  Mia and Me   TV-Y          2015
988                                  Paddington     PG          2014
989                             Russell Madness     PG          2015
990                           My Animal Friends   TV-Y          2013
991                          Dawn of the Croods  TV-Y7          2017
992                  Alpha and Omega: Dino Digs   TV-G          2016
993                   Wiener Dog Internationals      G          2015
994                                    Pup Star      G          2016
995                                     The BFG     PG          2016
996                     The Secret Life of Pets     PG          2016
997                            Precious Puppies   TV-G          2003
998                                 Beary Tales   TV-G          2013
999                             Growing Up Wild      G          2016

[1000 rows x 3 columns]

Ad hoc # 특정 문제에는 특정 해결만 있다.(일반적인 해답이 없다.)<br/>
no free lunch # 특정한 목적에는 특정한 노력을 해야한다. (일반적인 해답이 없다.)

In [ ]:
df = pd.read_csv("data-netflix.csv", na_values= ['']) 
#널값도 정할 수 잇따. NA -> not available #ad hoc 
#강사는 안씀

In [ ]:
df = pd.read_csv("data-netflix.csv", skip_blank_lines=False) #빈줄 생각할까?

In [ ]:
df = pd.read_csv("data-netflix.csv", skiprows=[1,3,7]) #해당 인덱스 삭제

In [ ]:
df = pd.read_csv("data-netflix.csv", skipfooter=2, engine='python') 
# c-->1 python -> 5 ~100배 병목현상에서는 c언어  
# c -> 한글이나 이상한거 나오면 골치가 아파 3 
# 파이썬은 기본이 유니코드

In [66]:
import seaborn as sns

In [69]:
data = sns.load_dataset('tips', engine ='python')
#안불러오지면 encoding , engine = 'python'

In [72]:
type(data)

pandas.core.frame.DataFrame

In [73]:
data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
6          8.77  2.00    Male     No   Sun  Dinner     2
7         26.88  3.12    Male     No   Sun  Dinner     4
8         15.04  1.96    Male     No   Sun  Dinner     2
9         14.78  3.23    Male     No   Sun  Dinner     2
10        10.27  1.71    Male     No   Sun  Dinner     2
11        35.26  5.00  Female     No   Sun  Dinner     4
12        15.42  1.57    Male     No   Sun  Dinner     2
13        18.43  3.00    Male     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
15        21.58  3.92    Male     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
17        16.29  3.71    Male     No   Sun  Dinner     3
18        16.97  3.50  Female     No   Sun  Dinner     3
19        20.65  3.35    Male     No   Sat  Dinner     3
20        17.92  4.08    Male     No   Sat  Dinner     2
21        20.29  2.75  Female     No   Sat  Dinner     2
22        15.77  2.23  Female     No   Sat  Dinner     2
23        39.42  7.58    Male     No   Sat  Dinner     4
24        19.82  3.18    Male     No   Sat  Dinner     2
25        17.81  2.34    Male     No   Sat  Dinner     4
26        13.37  2.00    Male     No   Sat  Dinner     2
27        12.69  2.00    Male     No   Sat  Dinner     2
28        21.70  4.30    Male     No   Sat  Dinner     2
29        19.65  3.00  Female     No   Sat  Dinner     2
..          ...   ...     ...    ...   ...     ...   ...
214       28.17  6.50  Female    Yes   Sat  Dinner     3
215       12.90  1.10  Female    Yes   Sat  Dinner     2
216       28.15  3.00    Male    Yes   Sat  Dinner     5
217       11.59  1.50    Male    Yes   Sat  Dinner     2
218        7.74  1.44    Male    Yes   Sat  Dinner     2
219       30.14  3.09  Female    Yes   Sat  Dinner     4
220       12.16  2.20    Male    Yes   Fri   Lunch     2
221       13.42  3.48  Female    Yes   Fri   Lunch     2
222        8.58  1.92    Male    Yes   Fri   Lunch     1
223       15.98  3.00  Female     No   Fri   Lunch     3
224       13.42  1.58    Male    Yes   Fri   Lunch     2
225       16.27  2.50  Female    Yes   Fri   Lunch     2
226       10.09  2.00  Female    Yes   Fri   Lunch     2
227       20.45  3.00    Male     No   Sat  Dinner     4
228       13.28  2.72    Male     No   Sat  Dinner     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
230       24.01  2.00    Male    Yes   Sat  Dinner     4
231       15.69  3.00    Male    Yes   Sat  Dinner     3
232       11.61  3.39    Male     No   Sat  Dinner     2
233       10.77  1.47    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [74]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
total_bill    244 non-null float64
tip           244 non-null float64
sex           244 non-null category
smoker        244 non-null category
day           244 non-null category
time          244 non-null category
size          244 non-null int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.2 KB

In [75]:
data.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [76]:
data.sample()

    total_bill   tip   sex smoker  day    time  size
34       17.78  3.27  Male     No  Sat  Dinner     2

# numpy

In [1]:
df = pd.read_csv("data-netflix.csv", nrows=100) 
# 테스트 해볼 때, 1000만개중에서 몇개만 가져온다. 프로토타입 분석할 때 쓰임
df.shape
# df.info하면 할 필요가 없어  
# 판다스는 넘파이도 포함한다. 
# 수치해석은 정확도가 중요하다.
#  넘파이는 수치해성의 기본라이브러리 속도가 빨라 
#  판다스는 넘파이 기반이다.

(100, 7)

In [78]:
df = pd.read_excel("data-netflix.xlsx", sheetname=0)
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'data-netflix.xlsx'

In [79]:
movies_json= pd.read_json('data-netflix.json')

In [80]:
movies_json

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
10,Once Upon a Time,TV-PG,Parental guidance suggested. May not be suitab...,70,2016,98.0,80
100,The Life Aquatic with Steve Zissou,R,"language, some drug use, violence and partial ...",100,2004,NaN,82
101,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
102,The L Word,TV-MA,For mature audiences. May not be suitable for...,110,2009,NaN,82
103,The Office (U.S.),TV-14,Parents strongly cautioned. May be unsuitable ...,90,2012,97.0,80
104,30 Rock,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2012,66.0,80
105,Mad Men,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2014,75.0,80
106,It's Always Sunny in Philadelphia,TV-MA,For mature audiences. May not be suitable for...,110,2016,91.0,80
107,Californication,TV-MA,For mature audiences. May not be suitable for...,110,2014,63.0,80
108,Parks and Recreation,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2015,94.0,80
109,Friends,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2003,98.0,80
11,Sherlock,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,95.0,80
110,Shameless (U.S.),TV-MA,For mature audiences. May not be suitable for...,110,2016,97.0,80
111,Portlandia,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,62.0,80
112,New Girl,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,91.0,80
113,Don't Trust the B---- in Apartment 23,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2012,NaN,82
114,Friends with Benefits,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2011,NaN,82
115,The Client List,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2013,92.0,80
116,Halt and Catch Fire,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,NaN,82
117,5 to 7,R,some sexual material,100,2014,NaN,82
118,Marvel's Iron Fist,TV-MA,None,110,2017,98.0,80
119,Chef's Table,TV-MA,For mature audiences. May not be suitable for...,110,2017,NaN,82
12,Death Note,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2006,77.0,80
120,Documentary Now!,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,NaN,82
121,Grace and Frankie,TV-MA,For mature audiences. May not be suitable for...,110,2017,90.0,80
122,Better Call Saul,TV-MA,For mature audiences. May not be suitable for...,110,2016,95.0,80
123,The Get Down,TV-MA,For mature audiences. May not be suitable for...,110,2017,80.0,80
124,Schitt's Creek,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,74.0,80
...,...,...,...,...,...,...,...
972,D2: The Mighty Ducks,PG,some mild language and rough hockey action,60,1994,70.0,80
973,"Honey, I Shrunk the Kids",PG,Parental guidance suggested. May not be suitab...,60,1989,80.0,80
974,The Iron Giant,PG,fantasy action and mild language,60,1999,83.0,80
975,The Fox and the Hound 2,G,General Audiences. Suitable for all ages.,35,2006,NaN,82
976,Air Buddies,PG,"some mild, rude humor",60,2006,NaN,82
977,Dr. Dolittle: Tail to the Chief,PG,brief mild language and some rude behavior,60,2008,NaN,82
978,Flicka 2,PG,some reckless behavior,60,2010,NaN,82
979,H2O: Just Add Water,TV-PG,Parental guidance suggested. May not be suitab...,70,2009,74.0,80
98,Cheer Squad,TV-PG,None,70,2016,61.0,80
980,The Gruffalo,TV-Y,Suitable for all ages.,10,2009,NaN,82
981,Dolphin Tale,PG,some mild thematic elements,60,2011,NaN,82
982,Pound Puppies,TV-Y,Suitable for all ages.,10,2013,NaN,82
983,Beverly Hills Chihuahua 3: Viva La Fiesta!,G,General Audiences. Suitable for all ages.,35,2012,NaN,82
984,The Magic School Bus,TV-Y,Suitable for all ages.,10,1997,81.0,80
985,Step Dogs,TV-PG,Parental guidance suggested. May not be suitab...,70,2013,NaN,82
986,PokÃ©mon: Indigo League,TV-Y,Suitable for all ages.,10,2000,74.0,80
987,Mia and Me,TV-Y,Suitable for all ages.,10,2015,NaN,82
988,Paddington,PG,mild action and rude humor,60,2014,70.0,80
989,Russell Madness,PG,some rude humor and sports action,60,2015,NaN,82
99,Only for One Night,TV-MA,None,110,2016,78.0,80
990,My Animal Friends,TV-Y,Suitable for all ages.,10,2013,NaN,82
991,Dawn of the Croods,TV-Y7,Suitable for children ages 7 and older,41,2017,72.0,80
992,Alpha and Omega: Dino Digs,TV-G,Suitable for all ages.,35,2016,NaN,82
993,Wiener Dog Internationals,G,General Audiences. Suitable for all ages.,35,2015,NaN,82
994,Pup Star,G,General Audiences. Suitable for all ages.,35,2016,NaN,82
995,The BFG,PG,"for action/peril, some scary moments and brief...",60,2016,97.0,80
996,The Secret Life of Pets,PG,for action and some rude humor,60,2016,NaN,81
997,Precious Puppies,TV-G,Suitable for all ages.,35,2003,NaN,82
998,Beary Tales,TV-G,Suitable for all ages.,35,2013,NaN,82
999,Growing Up Wild,G,None,35,2016,80.0,80

In [81]:
movies_json.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 7 columns):
title                1000 non-null object
rating               1000 non-null object
ratingLevel          941 non-null object
ratingDescription    1000 non-null int64
release year         1000 non-null int64
user rating score    605 non-null float64
user rating size     1000 non-null int64
dtypes: float64(1), int64(3), object(3)
memory usage: 62.5+ KB

In [82]:
#html 데이터는 우아하지 않아, 미쳐버려-> beautifulsoup or lxml
# 테이블 데이터는 잘 불러와

In [1]:
df = pd.read_pickle('data-netflix.p') 
#파이썬에서 객체를 저장할 때  #직렬화 방식 
# 예전에 버전에러가 나서 신뢰하지 않은 프로그래머가 많아짐
df.head()

,title,rating,ratingLevel,ratingDescription,release year,user rating score,user rating size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80

In [2]:
type(df)

pandas.core.frame.DataFrame

In [84]:
# 중간 저장 값을 피클로 저장
# 피클은 확장자 내맘대러 만들 수 잇다.

In [85]:
import sqlite3

In [86]:
conn = sqlite3.connect('data-netflix.sqlite')

In [87]:
df = pd.read_sql_query("select * from data_netflix", conn)

In [88]:
df.head()

,ogc_fid,title,rating,ratinglevel,ratingdescription,release year,user rating score,user rating size
0,1,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82,80
1,2,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NA,82
2,3,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98,80
3,4,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98,80
4,5,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94,80

In [89]:
# dataframe 만드는 방법 3가지 (class)
# 함수로 만드는방법(read_)
# 인스턴스 
# from 방법  (to ~)

In [97]:
df = pd.read_csv("data-netflix.csv", encoding='utf-8')

In [98]:
df.to_html('ss.html')

UnicodeEncodeError: 'cp949' codec can't encode character '\xc3' in position 5271: illegal multibyte sequence

In [1]:
df = pd.read_csv('data-netflix.csv')
df['title'] # dict 판다스는 여러개 복수가 있으면 list
df[['title','rating']]

                                          title rating
0                                  White Chicks  PG-13
1                           Lucky Number Slevin      R
2                                Grey's Anatomy  TV-14
3                                  Prison Break  TV-14
4                         How I Met Your Mother  TV-PG
5                                  Supernatural  TV-14
6                                  Breaking Bad  TV-MA
7                           The Vampire Diaries  TV-14
8                              The Walking Dead  TV-MA
9                           Pretty Little Liars  TV-14
10                             Once Upon a Time  TV-PG
11                                     Sherlock  TV-14
12                                   Death Note  TV-14
13                                       Naruto  TV-PG
14                                   The Hunter      R
15                        Lottie Dottie Chicken   TV-Y
16                                        Arrow  TV-14
17                                 Black Mirror  TV-MA
18                                The Originals  TV-14
19                                      The 100     NR
20                           Masha and the Bear   TV-Y
21                    Ã“ Pai, Ã“ - Look at This  TV-MA
22                       Nymphomaniac: Volume 1     NR
23                       Hunter X Hunter (2011)     NR
24                           Marvel's Luke Cage  TV-MA
25                           Marvel's Iron Fist  TV-MA
26                                       Narcos  TV-MA
27                                    The Flash  TV-PG
28                        The Seven Deadly Sins  TV-14
29                                       Scream  TV-14
..                                          ...    ...
970                                       Annie     PG
971          An American Tail: Fievel Goes West      G
972                        D2: The Mighty Ducks     PG
973                    Honey, I Shrunk the Kids     PG
974                              The Iron Giant     PG
975                     The Fox and the Hound 2      G
976                                 Air Buddies     PG
977             Dr. Dolittle: Tail to the Chief     PG
978                                    Flicka 2     PG
979                         H2O: Just Add Water  TV-PG
980                                The Gruffalo   TV-Y
981                                Dolphin Tale     PG
982                               Pound Puppies   TV-Y
983  Beverly Hills Chihuahua 3: Viva La Fiesta!      G
984                        The Magic School Bus   TV-Y
985                                   Step Dogs  TV-PG
986                     PokÃ©mon: Indigo League   TV-Y
987                                  Mia and Me   TV-Y
988                                  Paddington     PG
989                             Russell Madness     PG
990                           My Animal Friends   TV-Y
991                          Dawn of the Croods  TV-Y7
992                  Alpha and Omega: Dino Digs   TV-G
993                   Wiener Dog Internationals      G
994                                    Pup Star      G
995                                     The BFG     PG
996                     The Secret Life of Pets     PG
997                            Precious Puppies   TV-G
998                                 Beary Tales   TV-G
999                             Growing Up Wild      G

[1000 rows x 2 columns]

In [2]:
df['title'] # dataframe 한 컬럼은 시리즈

0                                    White Chicks
1                             Lucky Number Slevin
2                                  Grey's Anatomy
3                                    Prison Break
4                           How I Met Your Mother
5                                    Supernatural
6                                    Breaking Bad
7                             The Vampire Diaries
8                                The Walking Dead
9                             Pretty Little Liars
10                               Once Upon a Time
11                                       Sherlock
12                                     Death Note
13                                         Naruto
14                                     The Hunter
15                          Lottie Dottie Chicken
16                                          Arrow
17                                   Black Mirror
18                                  The Originals
19                                        The 100
20                             Masha and the Bear
21                      Ã“ Pai, Ã“ - Look at This
22                         Nymphomaniac: Volume 1
23                         Hunter X Hunter (2011)
24                             Marvel's Luke Cage
25                             Marvel's Iron Fist
26                                         Narcos
27                                      The Flash
28                          The Seven Deadly Sins
29                                         Scream
                          ...
970                                         Annie
971            An American Tail: Fievel Goes West
972                          D2: The Mighty Ducks
973                      Honey, I Shrunk the Kids
974                                The Iron Giant
975                       The Fox and the Hound 2
976                                   Air Buddies
977               Dr. Dolittle: Tail to the Chief
978                                      Flicka 2
979                           H2O: Just Add Water
980                                  The Gruffalo
981                                  Dolphin Tale
982                                 Pound Puppies
983    Beverly Hills Chihuahua 3: Viva La Fiesta!
984                          The Magic School Bus
985                                     Step Dogs
986                       PokÃ©mon: Indigo League
987                                    Mia and Me
988                                    Paddington
989                               Russell Madness
990                             My Animal Friends
991                            Dawn of the Croods
992                    Alpha and Omega: Dino Digs
993                     Wiener Dog Internationals
994                                      Pup Star
995                                       The BFG
996                       The Secret Life of Pets
997                              Precious Puppies
998                                   Beary Tales
999                               Growing Up Wild
Name: title, Length: 1000, dtype: object

In [4]:
df[['title']] #dataframe 2차원

                                          title
0                                  White Chicks
1                           Lucky Number Slevin
2                                Grey's Anatomy
3                                  Prison Break
4                         How I Met Your Mother
5                                  Supernatural
6                                  Breaking Bad
7                           The Vampire Diaries
8                              The Walking Dead
9                           Pretty Little Liars
10                             Once Upon a Time
11                                     Sherlock
12                                   Death Note
13                                       Naruto
14                                   The Hunter
15                        Lottie Dottie Chicken
16                                        Arrow
17                                 Black Mirror
18                                The Originals
19                                      The 100
20                           Masha and the Bear
21                    Ã“ Pai, Ã“ - Look at This
22                       Nymphomaniac: Volume 1
23                       Hunter X Hunter (2011)
24                           Marvel's Luke Cage
25                           Marvel's Iron Fist
26                                       Narcos
27                                    The Flash
28                        The Seven Deadly Sins
29                                       Scream
..                                          ...
970                                       Annie
971          An American Tail: Fievel Goes West
972                        D2: The Mighty Ducks
973                    Honey, I Shrunk the Kids
974                              The Iron Giant
975                     The Fox and the Hound 2
976                                 Air Buddies
977             Dr. Dolittle: Tail to the Chief
978                                    Flicka 2
979                         H2O: Just Add Water
980                                The Gruffalo
981                                Dolphin Tale
982                               Pound Puppies
983  Beverly Hills Chihuahua 3: Viva La Fiesta!
984                        The Magic School Bus
985                                   Step Dogs
986                     PokÃ©mon: Indigo League
987                                  Mia and Me
988                                  Paddington
989                             Russell Madness
990                           My Animal Friends
991                          Dawn of the Croods
992                  Alpha and Omega: Dino Digs
993                   Wiener Dog Internationals
994                                    Pup Star
995                                     The BFG
996                     The Secret Life of Pets
997                            Precious Puppies
998                                 Beary Tales
999                             Growing Up Wild

[1000 rows x 1 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
title                1000 non-null object
rating               1000 non-null object
ratingLevel          941 non-null object
ratingDescription    1000 non-null int64
release year         1000 non-null int64
user rating score    605 non-null float64
user rating size     1000 non-null int64
dtypes: float64(1), int64(3), object(3)
memory usage: 54.8+ KB

In [42]:
df = pd.read_csv('data-netflix.csv',engine='python')

In [43]:
df.to_html('tt.html')