In [1]:
import pandas as pd

In [49]:
df = pd.read_csv("apt_final.csv")

In [50]:
df

,price_per_area,price,con_year,year,dong,aptnm,month,dat,area,area_sub,...,seoul_cons_ratio,bond_one_year,bond_three_year,bond_five_year,bond_ten_year,corp_bond_yield_rate,call_rate,interest,interest_on_loan,cd
0,1979,71000.0,1982,2009,개포동,개포주공 3단지,10,1~10,35.87,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
1,1994,83700.0,1982,2009,개포동,개포주공 1단지,10,1~10,41.98,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
2,1128,173500.0,2004,2009,개포동,개포자이(12-2),10,1~10,153.80,large,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
3,1204,65000.0,1983,2009,개포동,개포주공 5단지,10,1~10,53.98,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
4,1214,160000.0,1986,2009,개포동,현대2,10,1~10,131.83,large,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
5,1480,75000.0,1982,2009,개포동,개포주공 4단지,10,1~10,50.67,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
6,1030,82000.0,1987,2009,개포동,우성8,10,11~20,79.61,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
7,1275,78000.0,1983,2009,개포동,개포주공 5단지,10,11~20,61.19,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
8,1975,100000.0,1982,2009,개포동,개포주공 1단지,10,11~20,50.64,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
9,1133,44800.0,1992,2009,개포동,성원대치2단지아파트,10,11~20,39.53,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
10,1115,37000.0,1992,2009,개포동,성원대치2단지아파트,10,11~20,33.18,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
11,1063,53000.0,1992,2009,개포동,성원대치2단지아파트,10,11~20,49.86,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
12,2223,112000.0,1982,2009,개포동,개포주공 4단지,10,11~20,50.39,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
13,1284,78000.0,1983,2009,개포동,개포주공 7단지,10,11~20,60.76,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
14,1905,80000.0,1982,2009,개포동,개포주공 4단지,10,11~20,41.99,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
15,2240,113500.0,1982,2009,개포동,개포주공 4단지,10,11~20,50.67,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
16,1200,66000.0,1987,2009,개포동,개포6차우성아파트1동~8동,10,11~20,54.98,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
17,938,98000.0,1984,2009,개포동,개포우성3차,10,11~20,104.43,large,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
18,1320,110500.0,1983,2009,개포동,개포주공 7단지,10,21~31,83.70,medium,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
19,1394,116000.0,1983,2009,개포동,개포주공 6단지,10,21~31,83.21,medium,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
20,1880,80000.0,1982,2009,개포동,개포주공 1단지,10,21~31,42.55,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
21,1906,80000.0,1982,2009,개포동,개포주공 1단지,10,21~31,41.98,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
22,1937,98100.0,1982,2009,개포동,개포주공 1단지,10,21~31,50.64,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
23,1945,98500.0,1982,2009,개포동,개포주공 1단지,10,21~31,50.64,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
24,1936,69000.0,1982,2009,개포동,개포주공 1단지,10,21~31,35.64,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
25,1036,52950.0,1992,2009,개포동,삼익대청아파트,10,21~31,51.12,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
26,1016,136500.0,2004,2009,개포동,개포자이(12-2),10,21~31,134.30,large,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
27,1922,68500.0,1982,2009,개포동,개포주공 1단지,10,21~31,35.64,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
28,1868,79500.0,1982,2009,개포동,개포주공 4단지,10,21~31,42.55,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
29,2058,52000.0,1982,2009,개포동,주공2,10,21~31,25.27,small,...,10.061728,3.52,4.47,4.91,5.45,5.60,1.99,3.51,5.88,2.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429436,385,31000.0,1995,2017,중화동,삼익,2,1~10,80.58,medium,...,5.270756,1.47,1.67,1.86,2.16,2.13,1.23,1.49,3.45,1.49
429437,541,45800.0,2013,2017,중화동,동양엔파트2차,2,1~10,84.63,medium,...,5.270756,1.47,1.67,1.86,2.16,2.13,1.23,1.49,3.45,1.49
429438,381,22800.0,1998,2017,중화동,건영,2,1~10,59.85,small,...,5.270756,1.47,1.67,1.86,2.16,2.13,1.23,1.49,3.45,1.49
429439,569,34000.0,1998,2017,중화동,한신1차,2,11~20,59.76,small,...,5.270756,1.47,1.67,1.86,2.16,2.13,1.23,1.49,3.45,1.49
429440,470,39500.0,2010,2017,중화동,동양엔파트,2,11~20,84.10,medium,...,5.270756,1.47,1.67,1.86,2.16,2.13,1.23,1.49,3.45,1.49
429441,576,29000.0,1998,2017,중화동,한신1차,2,11~20,50.37,small,...,5.270756,1.47,1.67,1.86,2.16,2.13,1.23,1.49,3.45,1.49
429442,576,29000.0,1998,2017,중화동,한신1차,2,21~28,50.37,small,...,5.270756,1.47,1.67,1.86,2.16,2.13,1.23,1.49,3.45,1.49
429443,451,38000.0,1997,2017,중화동,한신1차,2,21~28,84.20,medium,...,5.270756,1.47,1.67,1.86,2.16,2.13,1.23,1.49,3.45,1.49
429444,425,25200.0,1995,2017,중화동,삼익,2,21~28,59.34,small,...,5.270756,1.47,1.67,1.86,2.16,2.13,1.23,1.49,3.45,1.49
429445,372,31300.0,1991,2017,중화동,극동,2,21~28,84.13,medium,...,5.270756,1.47,1.67,1.86,2.16,2.13,1.23,1.49,3.45,1.49
429446,574,34300.0,1998,2017,중화동,한신1차,2,21~28,59.76,small,...,5.270756,1.47,1.67,1.86,2.16,2.13,1.23,1.49,3.45,1.49
429447,586,35000.0,1998,2017,중화동,한신1차,12,1~10,59.76,small,...,6.285154,1.83,2.10,2.30,2.47,2.65,1.51,1.81,3.62,1.66
429448,506,42500.0,1997,2017,중화동,한신1차,12,1~10,84.03,medium,...,6.285154,1.83,2.10,2.30,2.47,2.65,1.51,1.81,3.62,1.66
429449,566,33800.0,1998,2017,중화동,한신1차,12,11~20,59.76,small,...,6.285154,1.83,2.10,2.30,2.47,2.65,1.51,1.81,3.62,1.66
429450,669,12000.0,2012,2017,중화동,범양프레체,12,11~20,17.94,small,...,6.285154,1.83,2.10,2.30,2.47,2.65,1.51,1.81,3.62,1.66
429451,617,36900.0,1998,2017,중화동,한신1차,12,11~20,59.76,small,...,6.285154,1.83,2.10,2.30,2.47,2.65,1.51,1.81,3.62,1.66
429452,586,35000.0,1998,2017,중화동,한신1차,12,11~20,59.76,small,...,6.285154,1.83,2.10,2.30,2.47,2.65,1.51,1.81,3.62,1.66
429453,454,26950.0,1995,2017,중화동,삼익,12,11~20,59.34,small,...,6.285154,1.83,2.10,2.30,2.47,2.65,1.51,1.81,3.62,1.66
429454,628,37500.0,1998,2017,중화동,한신1차,12,11~20,59.76,small,...,6.285154,1.83,2.10,2.30,2.47,2.65,1.51,1.81,3.62,1.66
429455,582,34800.0,1998,2017,중화동,한신1차,12,11~20,59.76,small,...,6.285154,1.83,2.10,2.30,2.47,2.65,1.51,1.81,3.62,1.66
429456,594,35500.0,1997,2017,중화동,한신1차,12,11~20,59.76,small,...,6.285154,1.83,2.10,2.30,2.47,2.65,1.51,1.81,3.62,1.66
429457,371,31500.0,1991,2017,중화동,극동,12,21~31,84.82,medium,...,6.285154,1.83,2.10,2.30,2.47,2.65,1.51,1.81,3.62,1.66
429458,527,44300.0,1997,2017,중화동,한신1차,12,21~31,84.03,medium,...,6.285154,1.83,2.10,2.30,2.47,2.65,1.51,1.81,3.62,1.66
429459,686,12300.0,2012,2017,중화동,범양프레체,12,21~31,17.94,small,...,6.285154,1.83,2.10,2.30,2.47,2.65,1.51,1.81,3.62,1.66
429460,472,40000.0,2004,2017,중화동,청원다미소,12,21~31,84.82,medium,...,6.285154,1.83,2.10,2.30,2.47,2.65,1.51,1.81,3.62,1.66
429461,601,35900.0,1998,2017,중화동,한신1차,12,21~31,59.76,small,...,6.285154,1.83,2.10,2.30,2.47,2.65,1.51,1.81,3.62,1.66
429462,582,34800.0,1998,2017,중화동,한신2,12,21~31,59.76,small,...,6.285154,1.83,2.10,2.30,2.47,2.65,1.51,1.81,3.62,1.66
429463,459,39000.0,2006,2017,중화동,미영리치타운103,12,21~31,84.90,medium,...,6.285154,1.83,2.10,2.30,2.47,2.65,1.51,1.81,3.62,1.66
429464,393,23500.0,1998,2017,중화동,건영,12,21~31,59.85,small,...,6.285154,1.83,2.10,2.30,2.47,2.65,1.51,1.81,3.62,1.66
429465,589,35200.0,1998,2017,중화동,한신2,12,21~31,59.76,small,...,6.285154,1.83,2.10,2.30,2.47,2.65,1.51,1.81,3.62,1.66

In [51]:
df.head()

,price_per_area,price,con_year,year,dong,aptnm,month,dat,area,area_sub,...,seoul_cons_ratio,bond_one_year,bond_three_year,bond_five_year,bond_ten_year,corp_bond_yield_rate,call_rate,interest,interest_on_loan,cd
0,1979,71000.0,1982,2009,개포동,개포주공 3단지,10,1~10,35.87,small,...,10.061728,3.52,4.47,4.91,5.45,5.6,1.99,3.51,5.88,2.79
1,1994,83700.0,1982,2009,개포동,개포주공 1단지,10,1~10,41.98,small,...,10.061728,3.52,4.47,4.91,5.45,5.6,1.99,3.51,5.88,2.79
2,1128,173500.0,2004,2009,개포동,개포자이(12-2),10,1~10,153.80,large,...,10.061728,3.52,4.47,4.91,5.45,5.6,1.99,3.51,5.88,2.79
3,1204,65000.0,1983,2009,개포동,개포주공 5단지,10,1~10,53.98,small,...,10.061728,3.52,4.47,4.91,5.45,5.6,1.99,3.51,5.88,2.79
4,1214,160000.0,1986,2009,개포동,현대2,10,1~10,131.83,large,...,10.061728,3.52,4.47,4.91,5.45,5.6,1.99,3.51,5.88,2.79

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 429466 entries, 0 to 429465
Data columns (total 62 columns):
price_per_area          429466 non-null int64
price                   429466 non-null float64
con_year                429466 non-null int64
year                    429466 non-null int64
dong                    429466 non-null object
aptnm                   429466 non-null object
month                   429466 non-null int64
dat                     429466 non-null object
area                    429466 non-null float64
area_sub                429466 non-null object
loc                     429466 non-null int64
floor                   429466 non-null int64
qrt                     429466 non-null object
yyyyqrt                 429466 non-null object
yyyym                   429466 non-null int64
gu                      429466 non-null object
num_children            429466 non-null int64
num_elementary          429466 non-null int64
num_middle              429466 non-null int64
num_high                429466 non-null int64
edu_subsidy             429466 non-null int64
basic_living            429466 non-null int64
hospital                429466 non-null int64
num_beds                429466 non-null int64
park_area               429466 non-null float64
salary_councilor        429466 non-null int64
obesity                 429466 non-null float64
total_in                429466 non-null int64
total_out               429466 non-null int64
inner_in                429466 non-null int64
inner_out               429466 non-null int64
outer_in                429466 non-null int64
outer_out               429466 non-null int64
city_in                 429466 non-null int64
city_out                429466 non-null int64
consm_price_idx         429466 non-null float64
food_price_idx          429466 non-null float64
prod_price_idx          429466 non-null float64
rental_house_idx        429466 non-null float64
pub_service_idx         429466 non-null float64
pri_service_idx         429466 non-null float64
source_price_idx        429466 non-null float64
life_price_idx          429466 non-null float64
debt                    429466 non-null int64
farm_assets             429466 non-null int64
none_farm_assets        429466 non-null int64
assets                  429466 non-null int64
current_assets          429466 non-null int64
current_debt_ratio      429466 non-null float64
asset_debt_ratio        429466 non-null float64
seoul_cons_result       429466 non-null int64
national_cons_result    429466 non-null int64
seoul_cons_ratio        429466 non-null float64
bond_one_year           429466 non-null float64
bond_three_year         429466 non-null float64
bond_five_year          429466 non-null float64
bond_ten_year           429466 non-null float64
corp_bond_yield_rate    429466 non-null float64
call_rate               429466 non-null float64
interest                429466 non-null float64
interest_on_loan        429466 non-null float64
cd                      429466 non-null float64
dtypes: float64(24), int64(31), object(7)
memory usage: 203.1+ MB

In [53]:
df.describe()

,price_per_area,price,con_year,year,month,area,loc,floor,yyyym,num_children,...,seoul_cons_ratio,bond_one_year,bond_three_year,bond_five_year,bond_ten_year,corp_bond_yield_rate,call_rate,interest,interest_on_loan,cd
count,429466.000000,429466.000000,429466.000000,429466.000000,429466.000000,429466.000000,429466.000000,429466.000000,429466.000000,429466.000000,...,429466.000000,429466.000000,429466.000000,429466.000000,429466.000000,429466.000000,429466.000000,429466.000000,429466.000000,429466.000000
mean,671.892266,52892.603109,1997.477384,2013.865475,6.451859,77.911301,11525.210832,8.713360,59304.020141,4522.020451,...,9.245226,4.887796,7.110189,2.689438,3.011828,3.051483,1.919451,2.267219,4.238880,2.144219
std,328.450378,36912.570766,9.403677,2.611333,3.251879,29.821640,164.825753,5.935531,74592.477578,1621.139380,...,5.245431,26.687804,28.952517,1.073088,1.151049,1.288442,0.612133,0.791415,0.926302,0.671695
min,10.000000,1000.000000,1961.000000,2009.000000,1.000000,10.321500,11110.000000,-4.000000,20091.000000,1114.000000,...,2.989699,1.260000,1.220000,1.250000,1.400000,1.650000,1.230000,1.310000,3.230000,1.340000
25%,448.000000,30000.000000,1989.000000,2012.000000,4.000000,59.580000,11350.000000,4.000000,20135.000000,3193.000000,...,5.936991,1.490000,1.690000,1.860000,2.180000,2.020000,1.280000,1.540000,3.440000,1.500000
50%,566.000000,42500.000000,1999.000000,2015.000000,6.000000,83.020000,11545.000000,8.000000,20158.000000,4318.000000,...,7.372126,1.980000,2.150000,2.300000,2.490000,2.570000,1.820000,2.040000,3.860000,1.990000
75%,799.000000,63500.000000,2005.000000,2016.000000,9.000000,84.970000,11680.000000,12.000000,20177.000000,5643.000000,...,10.463629,2.720000,3.380000,3.410000,3.650000,3.870000,2.480000,2.920000,5.340000,2.660000
max,4223.000000,790000.000000,2017.000000,2017.000000,12.000000,424.320000,11740.000000,68.000000,201712.000000,8163.000000,...,30.150327,266.000000,187.000000,4.910000,5.450000,7.340000,3.260000,4.160000,5.940000,3.590000

In [54]:
df.sample()

,price_per_area,price,con_year,year,dong,aptnm,month,dat,area,area_sub,...,seoul_cons_ratio,bond_one_year,bond_three_year,bond_five_year,bond_ten_year,corp_bond_yield_rate,call_rate,interest,interest_on_loan,cd
312623,506,30000.0,1999,2016,공릉동,태강아파트,10,21~31,59.34,small,...,11.374837,1.37,1.36,1.41,1.6,1.78,1.23,1.41,3.29,1.35

In [55]:
a = list( ["신사동", "압구정1동","압구정2동", "논현동","논현1동","논현2동", "청담동", "청담1동","청담2동", "삼성동","삼성1동","삼성2동","대치동","대치1동","대치2동","대치3동", "대치4동","역삼동","역삼1동","역삼2동","도곡동","도곡1동","도곡2동", "개포동","개포1동","개포2동", "개포3동","개포4동","일원본동", "일원동","일원1동","일원2동", "수서동","세곡동"])

In [56]:
b = set(a)

In [57]:
df['gu']

0         강남구
1         강남구
2         강남구
3         강남구
4         강남구
5         강남구
6         강남구
7         강남구
8         강남구
9         강남구
10        강남구
11        강남구
12        강남구
13        강남구
14        강남구
15        강남구
16        강남구
17        강남구
18        강남구
19        강남구
20        강남구
21        강남구
22        강남구
23        강남구
24        강남구
25        강남구
26        강남구
27        강남구
28        강남구
29        강남구
         ...
429436    중랑구
429437    중랑구
429438    중랑구
429439    중랑구
429440    중랑구
429441    중랑구
429442    중랑구
429443    중랑구
429444    중랑구
429445    중랑구
429446    중랑구
429447    중랑구
429448    중랑구
429449    중랑구
429450    중랑구
429451    중랑구
429452    중랑구
429453    중랑구
429454    중랑구
429455    중랑구
429456    중랑구
429457    중랑구
429458    중랑구
429459    중랑구
429460    중랑구
429461    중랑구
429462    중랑구
429463    중랑구
429464    중랑구
429465    중랑구
Name: gu, Length: 429466, dtype: object

In [58]:
b

{'개포1동',
 '개포2동',
 '개포3동',
 '개포4동',
 '개포동',
 '논현1동',
 '논현2동',
 '논현동',
 '대치1동',
 '대치2동',
 '대치3동',
 '대치4동',
 '대치동',
 '도곡1동',
 '도곡2동',
 '도곡동',
 '삼성1동',
 '삼성2동',
 '삼성동',
 '세곡동',
 '수서동',
 '신사동',
 '압구정1동',
 '압구정2동',
 '역삼1동',
 '역삼2동',
 '역삼동',
 '일원1동',
 '일원2동',
 '일원동',
 '일원본동',
 '청담1동',
 '청담2동',
 '청담동'}

In [59]:
df[df.isin(b)]

,price_per_area,price,con_year,year,dong,aptnm,month,dat,area,area_sub,...,seoul_cons_ratio,bond_one_year,bond_three_year,bond_five_year,bond_ten_year,corp_bond_yield_rate,call_rate,interest,interest_on_loan,cd
0,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,개포동,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429440,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429441,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429443,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429446,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429447,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429448,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429451,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429453,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429458,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429461,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429463,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429465,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
df[df.isin(b)].price_per_area.mean()

nan

In [ ]:
df[df.dong in (b)]

In [62]:
[1, 2, 3] in [[1,2,3],4]

True

In [63]:
df.dong in (b) # isin을 함수형 패러다임을 만든 이유

TypeError: 'Series' objects are mutable, thus they cannot be hashed

In [64]:
list(map(lambda x:x in b, df.dong)) #isin을 만듬

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 ...]

In [65]:
# 전체 칼람중에 내가원하는 칼럼이 있냐 없냐 
#isin